# Generated by Django 5.0.2 on 2024-02-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_name', models.CharField(max_length=100)),
                ('employ_number', models.CharField(max_length=10)),
                ('employ_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.department')),
            ],
        ),
    ]
